<?php
$ptdname='';
$ptdprice='';
$ptdquantity='';
$msg='Register';
$submitmessage='registerproducts';
$failed='';
$msgsc='';
$sale_prdt_name='';
$sale_prdt_price='';
$sale_prdt_quantity='';
$sale_prdt_total='';
?>